// Explicitly set Vertex AI configuration to avoid environment-level overrides
process.env.GOOGLE_CLOUD_LOCATION = 'us-central1';
process.env.GOOGLE_GENAI_USE_VERTEXAI = 'true';

const { 
  AgentTool, 
  FunctionTool, 
  GOOGLE_SEARCH, 
  LlmAgent, 
  InvocationContext, 
  createSession,
  PluginManager
} = require('@google/adk');
const { z } = require('zod');
const { sendWeatherMail } = require('./mailService');

console.log("--- Loading Advanced Weather Agent Core (Converted from Python) ---");

// 1. Google Search Agent
const googleSearchAgent = new LlmAgent({
  name: 'Weather_agent_google_search_agent',
  model: 'gemini-2.5-flash',
  description: 'Agent specialized in performing Google searches.',
  instruction: 'Use the GoogleSearchTool to find information on the web.',
  tools: [GOOGLE_SEARCH],
});

// 2. URL Context Agent (Custom implementation for Node as url_context is Python-specific)
const urlContextTool = new FunctionTool({
  name: 'UrlContextTool',
  description: 'Fetch content from a provided URL.',
  parameters: z.object({
    url: z.string().describe('The URL to fetch content from'),
  }),
  execute: async ({ url }) => {
    try {
      console.log(`[Tool] Fetching content from: ${url}`);
      const response = await fetch(url);
      const text = await response.text();
      return text.substring(0, 5000); // Limit context size
    } catch (error) {
      return `Error fetching URL: ${error.message}`;
    }
  }
});

const urlContextAgent = new LlmAgent({
  name: 'Weather_agent_url_context_agent',
  model: 'gemini-2.5-flash',
  description: 'Agent specialized in fetching content from URLs.',
  instruction: 'Use the UrlContextTool to retrieve content from provided URLs.',
  tools: [urlContextTool],
});

// 3. Email Tool (Preserved from existing Node implementation)
const sendEmailTool = new FunctionTool({
  name: 'email_agent',
  description: 'Send the email to the user for the requested place weather report',
  parameters: z.object({
    report: z.string().describe("Weather report generated by the weather_agent"),
    city: z.string().describe('Name of the city for the report'),
  }),
  execute: async ({ report, city }) => {
    console.log(`[Tool] email_agent execution for city: ${city}`);
    return await sendWeatherMail(report, city);
  }
});

// 4. Root Weather Agent
const weatherAgent = new LlmAgent({
  name: 'Weather_agent',
  model: 'gemini-2.5-flash',
  description: 'get the weather of the place entered by the user and sugest them if they should carry any object to save them fro that weather',
  instruction: `The agent will take in a inut of a city according to which the agent will get the weather of upcoming 7 days of that place and list it to user.
According to the weather you must suggest the user what should they wear and should they carry anything with them to save them from the weather. For example if the weather is rainy they should carry a umbrella or rain coat or if the uv index is high they should use sunscream and same according to other weathers.

Additionally, if the user asks for more details from a specific website, use the Weather_agent_url_context_agent.
Once you have generated the report, ASK the user if they want this report sent to their email. If they say YES, use the email_agent tool.`,
  tools: [
    new AgentTool({ agent: googleSearchAgent }),
    new AgentTool({ agent: urlContextAgent }),
    sendEmailTool
  ],
});

/**
 * Simplified runner that processes only the current input
 */
const runWeatherQuest = async (input) => {
  try {
    console.log(`[Service] Processing Input: "${input}"`);
    
    process.env.GOOGLE_CLOUD_LOCATION = 'us-central1';

    const session = createSession({
      appName: 'weather-quest',
      userId: 'anonymous-traveler',
    });

    const pluginManager = new PluginManager();

    const context = new InvocationContext({
      input: input,
      session: session,
      pluginManager: pluginManager
    });

    let finalContent = "";
    
    for await (const event of weatherAgent.runAsync(context)) {
      if (event.content) {
        if (typeof event.content === 'object' && event.content.parts) {
           finalContent = event.content.parts[0].text;
        } else if (typeof event.content === 'string') {
           finalContent = event.content;
        } else {
           finalContent = JSON.stringify(event.content);
        }
      }
      
      if (event.errorMessage) {
        console.error(`[Agent Event Error] ${event.errorCode}: ${event.errorMessage}`);
        throw new Error(`Oracle Error: ${event.errorMessage}`);
      }
    }

    return finalContent || "The Oracle is silent. Try asking about a specific city.";
  } catch (error) {
    console.error(`[Service] Agent Error: ${error.message}`);
    throw error;
  }
};

module.exports = { runWeatherQuest };
